new

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -70,10 +70,13 @@ jobs:
       - name: Create affected apps artifact file
         run: |
           echo '${{ steps.set-affected-apps.outputs.affected_apps }}' > affected-apps.json
-          
+          if [ ! -s affected-apps.json ]; then
+            echo "Error: affected-apps.json is empty or missing."
+            exit 1
+          fi
+
       - name: Upload affected apps as artifact
         uses: actions/upload-artifact@v3
         with:
           name: affected-apps
           path: affected-apps.json
-          # retention-days: 1
